services:
  talk:
    image: ghcr.io/leicraftmc/nextcloud-hpb:talk
    user: "1000"
    init: true
    healthcheck:
      start_period: 0s
      test: /healthcheck.sh
      interval: 30s
      timeout: 30s
      start_interval: 5s
      retries: 3
    ports:
      - ${TALK_PORT}:${TALK_PORT}/tcp
      - ${TALK_PORT}:${TALK_PORT}/udp
      - "8081:8081/tcp"
    environment:
      NC_DOMAIN_0: YOUR_NEXTCLOUD_DOMAIN         # domain of your nextcloud instance (e.g. cloud.example.com)
      SIGNALING_SECRET_0: YOUR_SIGNALING_SECRET  # secret for your signaling server for cloud.example.com
      TALK_HOST: YOUR_TALK_HOSTNAME              # hostname of your talk instance (e.g. turn.example.com)
      TURN_SECRET: YOUR_TURN_SECRET              # secret for your turn server
      TALK_PORT: 3478                            # port of your turn server 
      INTERNAL_SECRET: YOUR_INTERNAL_SECRET      # secret for internal communication
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /var/log/supervisord
      - /var/run/supervisord
      - /opt/eturnal/run
      - /conf
      - /tmp

networks:
  default:
    driver: bridge